FROM node:lts

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV CHROME_PATH=/usr/bin/chromium
ENV DEBIAN_FRONTEND=noninteractive

# Install chrome et al
RUN apt update -qq \
    && apt install -qq -y --no-install-recommends \
    curl \
    git \
    gnupg \
    libgconf-2-4 \
    libxss1 \
    libxtst6 \
    python3 \
    g++ \
    build-essential \
    chromium \
    chromium-sandbox \
    dumb-init \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /src/*.deb

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENTRYPOINT ["dumb-init", "-c", "--"]

# install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --frozen-lockfile --save-dev

# copy source code
COPY . .

# expose port
EXPOSE ${PORT}

# start
CMD [ "yarn", "start:dev" ]