name: Push image to Docker hub

# Note: The prereleased type will not trigger for pre-releases published
# from draft releases, but the published type will trigger. If you want
# a workflow to run when stable and pre-releases publish, subscribe to
# published instead of released and prereleased.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
    release:
        types: [published]

jobs:
    push_to_docker_hub:
        runs-on: ubuntu-latest
        name: Create new image and push to Docker Hub
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Hello world
              run: echo "Hello world... Push to docker"
