name: Push image to Docker hub

# Note: The prereleased type will not trigger for pre-releases published
# from draft releases, but the published type will trigger. If you want
# a workflow to run when stable and pre-releases publish, subscribe to
# published instead of released and prereleased.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
    release:
        types: [published]

jobs:
    push_to_docker_hub:
        runs-on: ubuntu-latest
        name: Create new image and push to Docker Hub
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DHIS2_BOT_DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DHIS2_BOT_DOCKER_HUB_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: dhis2/push-analytics
                  tags: |
                      type=semver,pattern={{raw}}

            # To debug
            - name: Output the tags
              run: echo "tags ${{ steps.meta.outputs.tags }}"
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
