name: Release to GitHub and Docker Hub

# We trigger releases manually
on: workflow_dispatch

jobs:
    # TODO: re-enable this (it has been tested and works well)
    # Only allow releases from the release branches branch
    # check_if_allowed:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Exit if branch is not a release branch
    #           # Add more branches if we want to release from there
    #           run: |
    #               if [ "${{ github.ref }}" = "refs/heads/master" ] || \
    #                  [ "${{ github.ref }}" = "refs/heads/alpha" ] || \
    #                  [ "${{ github.ref }}" = "refs/heads/beta" ] || \
    #                  [ "${{ github.ref }}" = "refs/heads/next" ] ||
    #               then
    #                   echo "On the master branch, release is allowed"
    #                   exit 0
    #               else
    #                   echo "Releases are only allowed from the master branch"
    #                   exit 1
    #               fi

    create_github_release:
        # Will not run if check_if_allowed fails
        # needs: check_if_allowed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'npm'
            - name: Install (dev) dependencies
              run: npm ci --include=dev
            - name: Lint code
              run: npm run lint
            - name: Run tests
              run: npm run test
            - name: Build the project
              run: npm run build
            - name: Compress the "/dist" directory
              id: compressed-dist
              # Send to dev/null to prevent long list of files in GHA output
              run: |
                  tar -zcvf ./push-analytics.tar.gz ./dist >/dev/null 2>&1
                  echo "Size of 'push-analytics.tar.gz' is $(stat -c%s './push-analytics.tar.gz') bytes."
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx -y semantic-release

    # Create zip from build
    # Create GitHub release with changelog and include zip
    # Deploy to docker-hub

    # publish-gpr:
    #     needs: build
    #     runs-on: ubuntu-latest
    #     permissions:
    #         contents: read
    #         packages: write
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: actions/setup-node@v4
    #           with:
    #               node-version: 16
    #               registry-url: https://npm.pkg.github.com/
    #         - run: npm ci
    #         - run: npm publish
    #           env:
    #               NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
