name: Release to GitHub and Docker Hub

# We trigger releases manually
on:
    # TODO: I don't want to run this workflow on every push, but triggered manually instead
    # using `workflow_dispatch`, but that would only work from the master branch:
    # The workflow file must be committed in the default branch (master/main) if you want to
    # use the workflow_dispatch event.
    # https://github.com/orgs/community/discussions/25219#discussioncomment-3246909
    # So we use `push` for now should undo this once everything has been found to work.
    push
    # workflow_dispatch

jobs:
    # TODO: re-enable this (it has been tested and works well)
    # Only allow releases from the master branch
    # check_if_allowed:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Exit if branch is not master
    #           run: |
    #               if [ "${{ github.ref }}" = "refs/heads/master" ]
    #               then
    #                   echo "On the master branch, release is allowed"
    #                   exit 0
    #               else
    #                   echo "Releases are only allowed from the master branch"
    #                   exit 1
    #               fi

    build:
        # Avoid running this if check_if_allowed fails
        # needs: check_if_allowed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout
            - name: Setup NodeJS
              uses: actions/setup-node
              with:
                  node-version: lts/*
                  cache: 'npm'
            - name: Install dependencies (incl. devDependencies)
              run: npm ci --include=dev
            - name: Lint code
              run: npm run lint
            - name: Run tests
              run: npm run test
            - name: Build the project
              run: npm run build
            - name: Compress the "/dist" directory
              uses: a7ul/tar-action
              id: compress
              with:
                  command: c
                  files: |
                      ./dist
                  outPath: push-analytics.tar.gz

    # Create zip from build
    # Create GitHub release with changelog and include zip
    # Deploy to docker-hub

    # publish-gpr:
    #     needs: build
    #     runs-on: ubuntu-latest
    #     permissions:
    #         contents: read
    #         packages: write
    #     steps:
    #         - uses: actions/checkout
    #         - uses: actions/setup-node
    #           with:
    #               node-version: 16
    #               registry-url: https://npm.pkg.github.com/
    #         - run: npm ci
    #         - run: npm publish
    #           env:
    #               NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
