name: Verify Push Analytics Service

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize', 'labeled']
        branches: ['master', 'beta', 'next', 'alpha']

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Node JS
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'npm'
            - name: Install dependencies (incl. devDependencies)
              run: npm ci --include=dev
            - name: Build the project
              # Building includes TypeScript compilations so type errors are caught here too
              run: npm run build
            - name: Lint code
              run: npm run lint
            - name: Run tests
              run: npm run test

    prepare-e2e:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'e2e')
        steps:
            - name: Setup Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build local Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: false
                  load: true
                  tags: dhis2/push-analytics:local
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Spin up the E2E environment
              # Fake SMTP is not needed for the e2e tests
              run: cd ./e2e/docker && docker compose up -d web db db-dump post-install-scripts push-analytics

    run-e2e:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'e2e')
        needs: [verify, prepare-e2e]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Node JS
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'npm'
            - name: Install dependencies (incl. devDependencies)
              run: npm ci --include=dev
            - name: Run the test suite
              run: npm run e2e:test
